name: License

on:
  schedule:
  - cron: "0 0 * * 1"
  workflow_dispatch:
  
jobs:
  acquire_ulf:
    name: Acquire .ulf file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Unity Version
        id: unity-version
        run: |
          echo "UNITY_VERSION=$(cat ProjectSettings/ProjectVersion.txt | grep -oP 'm_EditorVersion: \K[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV
          echo "Unity version is $UNITY_VERSION
          
      - name: Request .alf file 🔑
        id: alfFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
     
      - name: Activate unity
        id: ulfFile
        uses: zxc30314/activate-unity@master
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          unity-alf-path: ${{ steps.alfFile.outputs.filePath  }}  

      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ steps.ulfFile.outputs.filePath }}

      - name: Update secret UNITY_LICENSE
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'UNITY_LICENSE'
          value: '${{ steps.ulfRead.outputs.content }}'
          token: ${{ secrets.ACCESS_TOKEN }}
