name: Git Commit Info

on: 
  workflow_dispatch:
  workflow_call:
  push:
    
jobs:
  declare_variables:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Declare some variables for Linux
      if: ${{ !cancelled() && runner.os == 'Linux' }}
      shell: pwsh
      run: |
          commit_message=$(git log -1 --no-merges --pretty=%B)
          echo "commit_message=$commit_message" >> $GITHUB_ENV
          echo $commit_message

    - name: Declare variables
      if: ${{ !cancelled() }}
      shell: pwsh
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
          $sha = "${{ github.event.pull_request.head.sha }}"
          $sha_short = $sha.Substring(0, 7)
          $branch_ref = $env:GITHUB_REF -replace '^refs/heads/', ''
          $converted_ref = $branch_ref -replace '^refs/pull/(\d+)/merge$', 'pull/$1'
          $url = "https://github.com/${{ github.repository }}/$converted_ref/commits/$sha"
        } else {
          $sha = "${{ github.sha }}"
          $sha_short = (git rev-parse --short $sha)
          $url = "https://github.com/${{ github.repository }}/commit/$sha"
        }

        $commit_message = git log -1 --no-merges --pretty=%B
        $authHeader = @{
          "Authorization" = "Bearer ${{ secret.ACCESS_TOKEN }}"
          "Accept" = "application/vnd.github.v3+json"
        }
        $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/commits/$sha" -Headers $authHeader
        $username = $response.author.login

        Write-Output "::set-output name=sha_short::$sha_short"
        Write-Output "::set-output name=url::$url"
        Write-Output "::set-output name=username::$username"
        Write-Output "::set-output name=commit_message::$commit_message"

