name: checklicense

on: 
  workflow_dispatch:
  workflow_call:
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: .
jobs:
  checklicense:
    name: check if UNITY_LICENSE is set in github secrets
    runs-on: ubuntu-latest
  #  runs-on: self-hosted
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether unity activation requests should be done
        id: checklicense_job
        run: |
            echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
            echo "is_unity_license_set=${{ env.UNITY_LICENSE != '' }}" >> $GITHUB_OUTPUT
  activation:
    needs: [checklicense]
    if: needs.checklicense.outputs.is_unity_license_set == 'false'
    name: Update License 🔑
    runs-on: ubuntu-latest
  #  runs-on: self-hosted
    steps:
     - uses: actions/checkout@master
     - name: Update License
       uses: ./.github/workflows/Activation.yml
