
name: Test

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Current branch name
      if: github.event_name == 'push'
      run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "main" the default branch that triggered the push event.
        
    - name: Get Head Ref branch name
      if: github.event_name == 'pull_request'
      run: |
        echo "${{ steps.branch-name.outputs.head_ref_branch }}"
        
    - name: Declare some variables on pr
      if: ${{ !cancelled() && github.event_name == 'pull_request'}} 
      shell: bash
      run: |
          branch_ref="${GITHUB_REF#refs/heads/}"
          converted_ref=$(echo "$branch_ref" | sed -n 's|refs/pull/\([0-9]*\)/merge|pull/\1|p')
          sha=${{github.event.pull_request.head.sha }}
          sha_short=$(echo "$sha" | cut -c 1-7)
          echo "sha_short=$sha_short" >> "$GITHUB_ENV"
          echo "message=$(git log -1 --no-merges --pretty=%B)" >> "$GITHUB_ENV"
          echo "username=$(curl -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" https://api.github.com/repos/${{ github.event.repository.full_name }}/commits/$sha | jq -r '.author.login')" >> "$GITHUB_ENV"
          echo "url=https://github.com/${{github.event.repository.full_name}}/$converted_ref/commits/$sha" >> "$GITHUB_ENV"

    - name: Declare some variables on push
      if: ${{ !cancelled() && env.url=='' }}
      shell: bash
      run: |
          sha_short=$(git rev-parse --short "$GITHUB_SHA")
          sha=${{ github.sha }}
          echo "sha_short=$sha_short" >> "$GITHUB_ENV"
          echo "message=$(git log -1 --no-merges --pretty=%B)" >> "$GITHUB_ENV"
          echo "username=$(curl -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" https://api.github.com/repos/${{ github.event.repository.full_name }}/commits/$sha | jq -r '.author.login')" >> "$GITHUB_ENV"
          echo "url=https://github.com/${{github.event.repository.full_name}}/commit/$sha" >> "$GITHUB_ENV"
      
    - name: Print converted branch reference
      run: |
          echo "sha_short: ${{ env.sha_short}}"
          echo "url: ${{ env.url}}"
          echo "message: ${{ env.message}}"
          echo "username: ${{ env.username}}"
          echo "${{github.event_name}}"
          
          
