name: Modify Unity Scripting Backend

on:
  push:
  workflow_dispatch:

jobs:
  modify-settings:
    runs-on: Windows  # 使用 Windows 环境来执行 PowerShell 脚本
    env:
      PROJECT_PATH: .
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify ProjectSettings.asset file
      run: |
        ls -Force ${env.PROJECT_PATH}
        $relativePath = "ProjectSettings\\ProjectSettings.asset"
        $fileContent = Get-Content -Path $relativePath
        
        # 输出文件内容
        Write-Output "File content:"
        Write-Output $fileContent
        
        # 执行替换操作
        $fileContent = $fileContent -replace '(scriptingBackend:\s*)(Standalone:\s*)0', '$1$2 1'
        
        # 输出修改后的内容
        Write-Output "Modified content:"
        Write-Output $fileContent

        # 保存修改后的内容
        Set-Content -Path $relativePath -Value $fileContent
      shell: pwsh
      env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}  # 通过 GitHub Secrets 管理项目路径

    - name: Commit changes (optional)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ProjectSettings/ProjectSettings.asset
        git commit -m "Update scriptingBackend setting"
        git push
