name: Modify Unity Scripting Backend

on:
  push:
  workflow_dispatch:

jobs:
  modify-settings:
    runs-on: Windows  # 使用 Windows 环境来执行 PowerShell 脚本

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify ProjectSettings.asset file
      run: |
        $projectSettingsFilePath = "${{env.PROJECT_PATH}}\\ProjectSettings\\ProjectSettings.asset"
        $fileContent = Get-Content -Path $projectSettingsFilePath
        $fileContent = $fileContent -replace '(scriptingBackend:\s*)(Standalone:\s*)0', '$1$2 1'

        # 输出修改后的内容
        Write-Output "Modified content:"
        Write-Output $fileContent

        # 将修改后的内容保存回文件
        Set-Content -Path $projectSettingsFilePath -Value $fileContent
      shell: pwsh
      env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}  # 通过 GitHub Secrets 管理项目路径

    - name: Commit changes (optional)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ProjectSettings/ProjectSettings.asset
        git commit -m "Update scriptingBackend setting"
        git push
