name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
         QODANA_TOKEN: ${{ secrets.QODANA }}
         QODANA_REMOTE_URL: https://github.com/${{ github.repository }}
         QODANA_BRANCH: ${{ github.head_ref }}
         QODANA_JOB_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
