name: Example workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: echo "::set-output name=my_output::$(echo 'Hello, World!' | cut -c 1-5)"

      - name: Use output
        run: echo "Output:+ ${{ steps.my_step.outputs.my_output }}"
