name: Example workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: |
          output=$(echo 'Hello, World!' | cut -c 1-5)
          echo "Output: $output"
          echo "::set-output name=my_output::$output"

      - name: Use output
        run: echo "Output:+ ${{ steps.my_step.outputs.my_output }}"
