
name: Unity Bulid

on:
  pull_request: 
    types:
      - opened
      - synchronize
    branches: 
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:
   inputs:
    version:
      required: true
      type: string
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: .

jobs:
  test:
    uses: ./.github/workflows/Test runner.yml
    secrets: inherit
    
  build:
    needs: [test]
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [ self-hosted, "${{ matrix.os }}" ]
    environment: 
      name: production
    strategy:
      fail-fast: false
      matrix:
        include:
         - os: Linux
           targetPlatform: Android
         - os: Windows
           targetPlatform: StandaloneWindows64
         # - StandaloneOSX
         # - StandaloneWindows
         # - StandaloneLinux64
         # - iOS
         # - WebGL
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      
      - name: Get Commit Info
        uses: zxc30314/git-commit-info@main
        id: info
        with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            
      # https://github.com/game-ci/unity-builder/releases/

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - name: Zip build file 
        shell: pwsh
        run: |
            $sourcePath = "${{ env.PROJECT_PATH }}/build/${{ matrix.targetPlatform }}"
            $destinationPath = "${{ matrix.targetPlatform }}.zip"
        
            if (-Not (Test-Path -Path $sourcePath)) {
                Write-Error "Source path '$sourcePath' does not exist."
                exit 1
            }
        
            Compress-Archive -Path "$sourcePath\*" -DestinationPath $destinationPath
            Write-Host "Build contents zipped to $destinationPath"
    
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HHmmSS
          utcOffset: "+08:00"
          
      - name: Upload to WebDAV
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{ secrets.WEBDAV_ADDRESS }}
          webdav_username: ${{ secrets.WEBDAV_USERNAME }}
          webdav_password: ${{ secrets.WEBDAV_PASSWORD }}
          webdav_upload_path: /${{ steps.current-time.outputs.formattedTime}}
          files: '${{matrix.targetPlatform}}.zip'


      - name: Send success message to Discord
        if: ${{success()}}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "[${{github.event.repository.name}}:${{github.ref_name}}] ${{matrix.targetPlatform}} has been deployed."
          embed-url: "${{secrets.WEBDAV_ADDRESS}}/${{ steps.current-time.outputs.formattedTime}}/${{matrix.targetPlatform}}.zip"
          embed-description: "[``${{steps.info.outputs.sha_short}}``](${{steps.info.outputs.url}}) ${{steps.info.outputs.commit_message}} -${{steps.info.outputs.username}}"
          embed-color: 7506394
          avatar-url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub
          embed-author-name: ${{github.event.sender.login}}
          embed-author-url: ${{github.event.sender.html_url}}
          embed-author-icon-url: ${{github.event.sender.avatar_url}}$

      - name: Get current job log URL
        if: ${{failure()}}
        uses: zxc30314/gha-jobid-action@main
        id: jobs
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          job_name: "Build for ${{ matrix.targetPlatform }}"

      - name: Send failure message to Discord
        if: ${{failure()}}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "[${{github.event.repository.name}}:${{github.ref_name}}] ${{github.workflow}} ${{matrix.targetPlatform}} failure"
          embed-url: "${{steps.jobs.outputs.html_url}}"
          embed-description: "[``${{steps.info.outputs.sha_short}}``](${{steps.info.outputs.url}}) ${{steps.info.outputs.commit_message}} -${{steps.info.outputs.username}}"
          embed-color: 16711680
          avatar-url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub
          embed-author-name: ${{github.event.sender.login}}
          embed-author-url: ${{github.event.sender.html_url}}
          embed-author-icon-url: ${{github.event.sender.avatar_url}}
        
        
          
          
