name: Git Commit Info

on:
  push:


jobs:
  declare_variables:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Declare some variables for Windows
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        $commit_message = $(git log -1 --no-merges --pretty=%B)
        echo "commit_message=$commit_message" >> $env:GITHUB_ENV

    - name: Declare some variables for Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        commit_message=$(git log -1 --no-merges --pretty=%B)
        echo "commit_message=$commit_message" >> $GITHUB_ENV

    - name: Display the commit message
      run: |
        echo "The commit message is: $commit_message"
