name: Git Commit Info

on:
  pull_request: 
    types:
      - opened
      - synchronize
    branches: 
      - 'main'
  push:

jobs:
  declare_variables:
    runs-on: Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Declare some variables
      if: ${{ !cancelled() }}
      run: |
        $commit_message = $(git log -1 --no-merges --pretty=%B)
        echo "commit_message=$commit_message" >> $env:GITHUB_ENV


    - name: Display the commit message
      run: |
        echo "The commit message is: $commit_message"
