name: Git Commit Info

on:
  push:
    branches:
      - main

jobs:
  declare_variables:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Declare some variables
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          commit_message=$(git log -1 --no-merges --pretty=%B)
          echo "commit_message=$commit_message" >> $GITHUB_ENV
        else
          commit_message=$(git log -1 --no-merges --pretty=%B)
          echo "commit_message=$commit_message" >> $GITHUB_ENV
        fi

    - name: Display the commit message
      run: |
        echo "The commit message is: $commit_message"
