name: Git Commit Info

on:
  pull_request: 
    types:
      - opened
      - synchronize
    branches: 
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  declare_variables:
    runs-on: Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Declare some variables
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        commit_message="$(git log -1 --no-merges --pretty=%B)"
        echo "commit_message=$commit_message" >> $GITHUB_ENV

    - name: Display the commit message
      run: |
        echo "The commit message is: $commit_message"
