name: Git Commit Info

on:
  push:


jobs:
  declare_variables:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [Windows, Linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Declare some variables
      if: ${{ !cancelled() }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
            # Windows 环境中的 PowerShell 语法
            $commit_message = $(git log -1 --no-merges --pretty=%B)
            echo "commit_message=$commit_message" >> $env:GITHUB_ENV
        } else {
            # Linux 环境中的 Bash 语法
            commit_message=$(git log -1 --no-merges --pretty=%B)
            echo "commit_message=$commit_message" >> $GITHUB_ENV
        }
    - name: Display the commit message
      run: |
        echo "The commit message is: $commit_message"
